version: '2'
services:
  php:
    image: fashionphile/php:0.0.7
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - elasticsearch
    environment:
      - PHP_IDE_CONFIG=serverName=docker-server
  apache:
    image: msteiner/apache:0.0.1
    environment:
      - WEB_PHP_SOCKET=php:9000
      - WEB_DOCUMENT_ROOT=/var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
  mysql:
    image: mysql:5.6.36
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    volumes:
      - data:/var/lib/mysql
  memcached:
    image: memcached:1.4.36
  elasticsearch:
    image: elasticsearch:1.4.5
    volumes:
      - esdata:/usr/share/elasticsearch/data
  dusk_tests:
    image: php:7.1.1-cli
    command: tail -f /dev/null
    volumes:
      - .:/var/www/html
    links:
      - selenium
  selenium:
    image: selenium/standalone-chrome:latest
    links:
      - "apache:fashionphile.integration"
      - "apache:www.fashionphile.integration"
volumes:
  data:
  esdata:
